# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: 'linux'
            platform: 'ubuntu-latest'
          - goos: 'windows'
            platform: 'windows-latest'
          - goos: 'darwin'
            platform: 'macos-latest'

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build
      run: |
        VERSION=${GITHUB_REF##*/}
        go build -o go-steam-restarter_${{ matrix.goos }}${{ matrix.goos == 'windows' && '.exe' || '' }} -ldflags "-X 'main.AppVersion=$VERSION'"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: go-steam-restarter_${{ matrix.goos }}${{ matrix.goos == 'windows' && '.exe' || '' }}

    - name: Publish new release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        files: go-steam-restarter_${{ matrix.goos }}${{ matrix.goos == 'windows' && '.exe' || '' }}
